site_name: 🤏🏻 investiny
site_url: https://github.com/alvarobartt/investiny
site_author: Alvaro Bartolome
site_description: investpy but made tiny

repo_name: alvarobartt/investiny
repo_url: https://github.com/alvarobartt/investiny

copyright: Copyright &copy; 2022 Alvaro Bartolome

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

plugins:
  - search:
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
  - mkdocstrings:

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/investiny/
    - icon: fontawesome/brands/github
      link: https://github.com/alvarobartt
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/alvarobartt
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alvarobartt/

nav:
  - Home: index.md
  - Differences with investpy: differences-with-investpy.md
  - Requirements: requirements.md
  - Installation: installation.md
  - Usage: usage.md
  - Limitations: limitations.md
  - Integrations: integrations.md
  - API Reference:
      - Historical: api/historical.md
      - Search: api/search.md
  - Disclaimer: disclaimer.md
  - License: license.md
